language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.5.*

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer install --dev --no-interaction
